title: MPIS Lab
email: zhaokbgshs@gmail.com
author: corbin zhao
logo: /static/img/avatar.png
about: corbin zhao
description: > 
  A Robotics, Machine Perception and Intelligent System lab by Corbin Zhao. The main focus of the blog is application of Deep Learning for Computer Vision tasks, as well as other relevant topics: classical Computer Vision, Numerical Methods and Hardware.
baseurl: ""
url: "https://corbining.github.io" # the base hostname & protocol 
twitter_username: corbining
github:  corbining

allowsearch: false
enableTags:  false

google_analytics: UA-104440412-1

paginate: 10
per_page: 10
paginate_path: "/blog/page:num/"
markdown: kramdown
kramdown:
  math_engine: mathjax

gems:
  - jekyll-paginate
  - jekyll-gist
  
exclude:
  - Gemfile
  - Gemfile.lock
